title: My personal website
author: Mathias Schaeffner
author_title: Photographer
email: mschaeffner@example.com
description: > # this means to ignore newlines until "twitter_username:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta.

sidebar_sections:
  - title: "About"
    text: "I am a photographer that like to go out into nature."
  - title: "Contact"
    text: "Just write me an email."

# social links
twitter_username: jekyllrb
github_username:  jekyll
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.md
 - projects.md
 - cv.html

# Build settings
theme: ceevee

plugins:
 - jekyll-seo-tag
